#!/bin/bash

# An example of a script using captain-control to generate proton in
# the volume of the LANSCE beam events in miniCAPTAIN.  This is
# actually pretty convenient to run from the command line.

source captain-control.bash

# Set the run number from the command line.
if [ ${#1} = 0 ]; then
    echo "Usage: $0 <run-number> <events>"
    captain-error "The run number must be provided."
fi

# Set the file name fields.
captain-experiment nb
captain-data-source pg
captain-run-type beam
captain-run-number ${1}
captain-processing-comment proton

DETSIM_MACRO=$(captain-file g4in)
cat <<EOF >> ${DETSIM_MACRO} 
####################################################################
# Start input
####################################################################
# Make sure to use a new seed.
/dsim/random/timeRandomSeed

# Run this in mini-captain
/dsim/control mini-captain 1.0

# Update the simulated geometry.
/dsim/update

####################################################################
# Define volume containing LANSCE neutron beam as it passes through
# the detector.

/gps/particle proton
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0. -55. -168. mm
/gps/pos/radius 100. mm
/gps/pos/halfz 600 mm 
/gps/pos/rot1 0 0 1
/gps/pos/rot2 -0.1188 1.0 0

####################################################################
# Define the angular distribution of the protons.

/gps/ang/type beam1d
/gps/ang/sigma_r 30 deg
/gps/ang/rot1 0 0 1
/gps/ang/rot2 -0.1188 1.0 0

###################################################################
# Define the energy distribution of the protons.  This is chosen to
# make reweighting by energy convenient.

/gps/ene/type Pow
/gps/ene/min 50 MeV
/gps/ene/max 800 MeV
/gps/ene/alpha -1.0

###################################################################
# End of input
###################################################################
EOF

# Check if the number of events to generate should be added to the file.
if [ ${#2} = 0 ]; then
    echo "Usage: $0 <run-number> <events>"
    captain-error "The number of events must be provided"
else
    captain-log Generating ${2} events.
    cat >> ${DETSIM_MACRO} <<EOF
/run/beamOn ${2}
EOF
fi

#####################################################
# The is the meat of the script: Run the DETSIM
#####################################################
captain-process-detsim-macro ${DETSIM_MACRO}

#####################################################
# Try to run ELECSIM, calibration, and reconstruction.
#####################################################
captain-run-reconstruction
